baseURL: https://devinstall.com
site_description: Setup a developer machine in a single command (Cross Platform)
site_name: DevInstall.com
repo_name: saul-salazar-dotcom/devinstall.com
repo_url: https://github.com/saul-salazar-dotcom/devinstall.com
site_url: https://www.devinstall.com/
copyright: Powered by Open Source Software. Logo and Favicon by <a href="https://icons8.com">icons8</a>

nav:
  - Home: index.md

theme:
  name: simple-blog
  favicon: assets/favicon.png
  logo: assets/favicon.png
  theme_style: white
  site_name_style: normal
  title_style: bold
  highlightjs: true
  hljs_languages: ["shell"]
  colors:
    text: black
    title: black
    primary: black
    background: white
  components:
    site_name: true
    title: true
    menu: true
    preview: true
    footer: true
